-- Information and help text are all stored here

local parser = parser

local M = {}
package.loaded[...] = M
if setfenv and type(setfenv) == "function" then
	setfenv(1,M)	-- Lua 5.1
else
	_ENV = M		-- Lua 5.2
end

VERSION = "1.20.07.23"

use = [[ROBODoc Version ]]..VERSION..[[(c) 1994-2020 Frans Slothouber, Petteri Kettunen,
				Gergely Budai, Jacco van Weert and Milind Gupta
	ROBODoc comes with ABSOLUTELY NO WARRANTY.
	This is free software, and you are welcome to redistribute it
    under certain conditions; type `robodoc -c' for details.]]
	
usage = [[Usage:
	robodoc --src <directory> --doc <directory> --multidoc   [type] [options]
	robodoc --src <directory> --doc <file>      --singledoc  [type] [options]
	robodoc --src <file>      --doc <file>      --singlefile [type] [options]

    Type:
	--html, --rtf, --latex, --ascii, --dbxml, --troff]]
	
-- options table
-- opt contains the option trigger
-- help contains the help description for the option
-- value is a table containing validation information for the option value. 
-- 		** The length of the table is the number of values allowed.
--		** Table values can be "string", "number", "file", {table of allowed values},"list" (comma separated elements),"listN" (N elements comma separated)
options = {
    {opt = "--charset",help="Add character encoding information (html only).",value ={"string"}},
    {opt = "--cmode",help="Use ANSI C grammar in source items (html only).",value={}},
    {opt="--css",help="Specify the stylesheet to use.",value={"file"}},
    {opt="--ext",help="Set extension for generated files.",value={"string"}},
    {opt="--footless",help="Do not create the foot of a document.",value={}},
    {opt="--headless",help="Do not create the head of a document.",value={}},
    {opt="--index",help="Add an index.",value={}},
    {opt="--internal",help="Also include internal headers.",value={}},
    {opt="--internalonly",help="Only include internal headers.",value={}},
    {opt="--lock",help="Recognize only one header marker per file.",value={}},
    {opt="--nodesc",help="Do not descent into subdirectories.",value={}},
    {opt="--no_subdirectories",help="Do no create documentation subdirectories.",value={}},
    {opt="--nopre",help="Do not use <PRE> </PRE> in the HTML output.",value={}},
    {opt="--nosort",help="Do not sort the headers.",value={}},
    {opt="--nosource",help="Do not include SOURCE items.",value={}},
    {opt="--nogeneratedwith",help="Do not add the 'generated by robodoc' message at the top of each documentation file.",value={}},
    {opt="--ignore_case_when_linking",help="Ignore the case of the symbols when trying to create crosslinks.",value={}},
    {opt="--rc",help="Specify an alternate configuration file.",value={"file"}},
    {opt="--sections",help="Add sections and subsections.",value={}},
    {opt="--first_section_level",help="Start the first section not at 1 but at level NUMBER.",value={"number"}},
    {opt="--tabsize",help="Set the tab size.",value={"number"}},
    {opt="--tabstops a,b,..,n",help="Set TAB stops ",value={"list"}},
    {opt="--tell",help="ROBODoc will tell you what it is doing.",value={}},
    {opt="--debug",help="same as --tell, but with lots more details.",value={}},
    {opt="--toc",help="Add a table of contents.",value={}},
    {opt="--version",help="Print version info and exit.",value={}},
    {opt="--sectionnameonly",help="Generate section header with name only.",value={}},
    {opt="--compress",help="Only supported by TROFF output format. Defines by which program manpages will be compressed. Either bzip2 or gzip.",value={{"bzip2","gzip"}},
    {opt="--mansection",help="Manual section where pages will be inserted (default: 3).",value={"number"}},
    {opt="--documenttitle",help="Set the document title",value={"string"}},
    {opt="--altlatex",help="Alternate LaTeX file format (bigger / clearer than normal)",value={}},
    {opt="--latexparts",help="Make the first module level as PART in LaTeX output",value={}},
    {opt="--syntaxcolors",help="Turn on all syntax highlighting features in SOURCE items (html only)",value={}},
    {opt="--syntaxcolors_enable quotes,squotes,line_comments,block_comments,keywords,non_alpha",help="Enable only specific syntax highlighting features in SOURCE items (html only)",value={}},
    {opt="--dotname NAME",help="Specify the name (and path / options) of DOT tool"},
    {opt="--masterindex title,filename",help="Specify the title and filename for master index page"},
    {opt="--sourceindex title,filename",help="Specify the title and filename for source files index page"},
    {opt="--one_file_per_header",help="Create a separate documentation file for each header"},
    {opt="--header_breaks NUMBER",help="Insert a linebreak after every NUMBER header names (default value: 2, set to zero to disable)"},
    {opt="--source_line_numbers",help="Display original source line numbers for SOURCE items"},
}

parser:option("--rc","Specify an alternate configuration file.","robodoc.rc",nil,1,1)

authors = {
	"Frans Slothouber",
	"Jacco van Weert",
	"Petteri Kettunen",
	"Bernd Koesling",
	"Thomas Aglassinger",
	"Anthon Pang",
	"Stefan Kost",
	"David Druffner",
	"Sasha Vasko",
	"Kai Hofmann", 
	"Thierry Pierron",
	"Friedrich Haase",
	"Gergely Budai",
	"Milind Gupta"
}

license = [[Distributed under the GNU GENERAL PUBLIC LICENSE
	TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
 See the source archive for a copy of the complete licence
 If you do not have it you can get it from URL
 http://www.gnu.org/copyleft/gpl.html
]] 